Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,91 +1,83 @@
-#!/bin/bash
-set -uex
-cd /tmp
+#!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir>
 
-# Heroku revision.  Must match in 'compile' program.
+# fail fast
+set -e
+
+# Heroku Revision.
 #
 # Affixed to all vendored binary output to represent changes to the
 # compilation environment without a change to the upstream version,
 # e.g. PHP 5.3.27 without, and then subsequently with, libmcrypt.
 heroku_rev='-2'
 
-# Clear /app directory
-find /app -mindepth 1 -print0 | xargs -0 rm -rf
+# config
+MCRYPT_VERSION="2.5.8"
+APACHE_VERSION="2.2.25"
+APACHE_PATH="apache"
+PHP_VERSION="5.3.27"
+PHP_PATH="php"
 
-# Take care of vendoring libmcrypt
-mcrypt_version=2.5.8
-mcrypt_dirname=libmcrypt-$mcrypt_version
-mcrypt_archive_name=$mcrypt_dirname.tar.bz2
+BIN_DIR=$(dirname $0)
+BUILD_DIR=$1
+CACHE_DIR=$2
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
 
-# Download mcrypt if necessary
-if [ ! -f mcrypt_archive_name ]
-then
-    curl -Lo $mcrypt_archive_name http://sourceforge.net/projects/mcrypt/files/Libmcrypt/2.5.8/libmcrypt-2.5.8.tar.bz2/download
-fi
+function download_and_install_ibm_db() {
+  CLI_URL="https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz"
 
-# Clean and extract mcrypt
-rm -rf $mcrypt_dirname
-tar jxf $mcrypt_archive_name
+  echo "Downloading IBM Data Server Driver...."
+  curl -LO "$CLI_URL"
 
-# Build and install mcrypt.
-pushd $mcrypt_dirname
-./configure --prefix=/app/vendor/mcrypt \
-  --disable-posix-threads --enable-dynamic-loading
-make -s
-make install -s
-popd
+  # Extracting and Cleaning DS Driver
+  rm -rf clidriver
+  tar -xzf linuxx64_odbc_cli.tar.gz
 
-# Take care of vendoring Apache.
-httpd_version=2.2.25
-httpd_dirname=httpd-$httpd_version
-httpd_archive_name=$httpd_dirname.tar.bz2
+  echo "Downloading autoconf..."
+  curl -LO http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
 
-# Download Apache if necessary.
-if [ ! -f $httpd_archive_name ]
-then
-    curl -LO https://archive.apache.org/dist/httpd/httpd-2.2.25.tar.bz2
-fi
+  echo "Downloading m4..."
+  curl -LO http://ftp.gnu.org/pub/gnu/m4/m4-1.4.13.tar.gz
 
-# Clean and extract Apache.
-rm -rf $httpd_dirname
-tar jxf $httpd_archive_name
+  # Extracting m4 and autoconf
+  tar -xzf autoconf-2.69.tar.gz
+  tar -xzf m4-1.4.13.tar.gz
 
-# Build and install Apache.
-pushd $httpd_dirname
-./configure --prefix=/app/apache --enable-rewrite --with-included-apr
-make -s
-make install -s
-popd
+  echo "Installing m4 and autoconf ..."
+  cd m4-1.4.13
+  ./configure --prefix=$BUILD_DIR/m4
+  make
+  make install
+  export PATH=$BUILD_DIR/m4/bin:$PATH
 
-# Take care of vendoring PHP.
-php_version=5.3.27
-php_dirname=php-$php_version
-php_archive_name=$php_dirname.tar.bz2
+  cd $BUILD_DIR/autoconf-2.69
+  ./configure --prefix=$BUILD_DIR/autoconf
+  make
+  make install
 
-# Download PHP if necessary.
-if [ ! -f $php_archive_name ]
-then
-    curl -Lo $php_archive_name http://us1.php.net/get/php-5.3.27.tar.bz2/from/www.php.net/mirror
-fi
+  cd $BUILD_DIR
+  #Cleaning clidriver, m4 and autoconf
+  rm -rf linuxx64_odbc_cli.tar.gz
+  rm -rf m4-1.4.13.tar.gz
+  rm -rf m4-1.4.13
+  rm -rf autoconf-2.69.tar.gz
+  rm -rf autoconf-2.69
 
-# Clean and extract PHP.
-rm -rf $php_dirname
-tar jxf $php_archive_name
+  ln -s $BUILD_DIR/php /app/php
+  ln -s $BUILD_DIR/vendor /app/vendor
 
-# Compile PHP
-pushd $php_dirname
-./configure --prefix=/app/php --with-apxs2=/app/apache/bin/apxs     \
---with-mysql --with-pdo-mysql --with-pgsql --with-pdo-pgsql         \
---with-iconv --with-gd --with-curl=/usr/lib                         \
---with-config-file-path=/app/php --enable-soap=shared               \
---with-openssl --with-mcrypt=/app/vendor/mcrypt --enable-sockets
-make -s
-make install -s
-popd
+  export PATH=$BUILD_DIR/autoconf/bin:/app/php/bin:$PATH
+  export IBM_DB_HOME=$BUILD_DIR/clidriver
+  export LD_LIBRARY_PATH=/app/vendor/mcrypt/lib:$LD_LIBRARY_PATH
+  export PHP_AUTOCONF=$BUILD_DIR/autoconf/bin/autoconf
+  export PHP_AUTOHEADER=$BUILD_DIR/autoconf/bin/autoheader
 
-# Copy in MySQL client library.
+  echo "Installing ibm_db2 ..."
+  pecl channel-update pecl.php.net
+  #pecl install ibm_db2
+  # Copy in MySQL client library.
 mkdir -p /app/php/lib/php
-cp /usr/lib/libmysqlclient.so.16 /app/php/lib/php
+#cp /usr/lib/libmysqlclient.so.16 /app/php/lib/php
 
 # 'apc' installation
 #
@@ -98,16 +90,83 @@ export PATH=/app/php/bin:$PATH
 # Use defaults for apc build prompts.
 yes '' | /app/php/bin/pecl install apc
 
-# Sanitize default cgi-bin to rid oneself of Apache sample
-# programs.
-find /app/apache/cgi-bin/ -mindepth 1 -print0 | xargs -0 rm -r
+}
+  
+# include .files when moving things around
+shopt -s dotglob
 
-# Stamp and archive binaries.
-pushd /app
-echo $mcrypt_version > vendor/mcrypt/VERSION
-tar -zcf mcrypt-"$mcrypt_version""$heroku_rev".tar.gz vendor/mcrypt
-echo $httpd_version > apache/VERSION
-tar -zcf apache-"$httpd_version""$heroku_rev".tar.gz apache
-echo $php_version > php/VERSION
-tar -zcf php-"$php_version""$heroku_rev".tar.gz php
-popd
+cd $BUILD_DIR
+
+# move app things to www
+mkdir -p $CACHE_DIR/www
+mv * $CACHE_DIR/www
+mv $CACHE_DIR/www .
+
+# keep Procfile
+if [ -f www/Procfile ]; then
+  mv www/Procfile .
+fi
+
+MCRYPT_URL="https://heroku-buildpack-php.s3.amazonaws.com/mcrypt-""$MCRYPT_VERSION""$heroku_rev"".tar.gz"
+echo "-----> Bundling mcrypt version $MCRYPT_VERSION"
+curl --silent --max-time 60 --location "$MCRYPT_URL" | tar xz
+
+APACHE_URL="https://heroku-buildpack-php.s3.amazonaws.com/apache-""$APACHE_VERSION""$heroku_rev"".tar.gz"
+echo "-----> Bundling Apache version $APACHE_VERSION"
+curl --silent --max-time 60 --location "$APACHE_URL" | tar xz
+
+PHP_URL="https://heroku-buildpack-php.s3.amazonaws.com/php-$PHP_VERSION""$heroku_rev"".tar.gz"
+echo "-----> Bundling PHP version $PHP_VERSION"
+curl --silent --max-time 60 --location "$PHP_URL" | tar xz
+
+# update config files
+cp $LP_DIR/conf/httpd.conf $APACHE_PATH/conf
+cp $LP_DIR/conf/php.ini php
+
+# Restore old artifacts from the cache.
+CACHED_DIRS="ibmdb2"
+for dir in $CACHED_DIRS; do
+  cp -R $CACHE_DIR/$dir/* . &> /dev/null || true
+done
+
+if [ -f clidriver/lib/libdb2.so ]; then
+  # we have from cache, just restore php's db2.so
+  echo "-------> restoring ibm_db2 from cache"
+  mv ibm_db2.so php/lib/php/extensions/no-debug-non-zts-20090626/
+  echo "-------> restored ibm_db2"
+else
+  echo "-------> downloading and installing ibm_db2"
+  download_and_install_ibm_db
+  echo "-------> caching ibm_db2 and dependencies"
+  for dir in $CACHED_DIRS; do
+    mkdir -p $CACHE_DIR/$dir
+    cp -R clidriver $CACHE_DIR/$dir &> /dev/null || true
+    cp php/lib/php/extensions/no-debug-non-zts-20090626/ibm_db2.so $CACHE_DIR/$dir &> /dev/null || true
+    echo "-------> caching ibm_db2 done"
+  done
+fi
+
+
+
+# make php available on bin
+mkdir -p bin
+ln -s /app/php/bin/php bin/php
+
+cat >>boot.sh <<EOF
+for var in \`env|cut -f1 -d=\`; do
+  echo "PassEnv \$var" >> /app/apache/conf/httpd.conf;
+done
+touch /app/apache/logs/error_log
+touch /app/apache/logs/access_log
+tail -F /app/apache/logs/error_log &
+tail -F /app/apache/logs/access_log &
+export LD_LIBRARY_PATH=/app/php/lib/php:/app/clidriver/lib
+export PHP_INI_SCAN_DIR=/app/www
+echo "Launching apache"
+exec /app/apache/bin/httpd -DNO_DETACH
+EOF
+
+chmod +x boot.sh
+
+# clean the cache
+#rm -rf $CACHE_DIR
